########################################################################
#
# Copyright (C) 2006 ESOC, ESA (www.esa.int)
#
# Description: 
#	Makefile for the Mdk/Management package of the SMP2 Adapter
#
# History:
#	See bottom of the file
#
########################################################################

Files = \
EntryPointPublisher \
EventConsumer \
EventProvider \
ManagedComponent \
ManagedModel \
ManagedObject 

include ../../../Makefile.top

all: $(BinDir) $(BIN_OBJECTS)

###########
# History #
###########

# $Log: Makefile,v $
# Revision 1.1  2006/05/05 23:22:59  nin
# Released
#